### ISSUE TITLE
TimeStepper design

### ISSUE THREAD

**Issue by santiagobadia** [gridap/GridapTimeStepper.jl#1]
Hi @fverdugo 

In [this file](https://github.com/gridap/GridapTimeStepper.jl/blob/master/src/GridapTimeStepper.jl) I have some notes about how I think we should implement the `TimeStepper` object in `Gridap`. Please take a look, it is just at an initial stage, before starting to implement anything.

If we agree with the basic design, I can start working on this. I would like to have at least Backward Euler and Crank-Nicolson concrete implementations in the near future.

**Comment by fverdugo** [comment]
@santiagobadia I have added a draft the ODE machinery here https://github.com/gridap/GridapTimeStepper.jl/blob/fverdugo_comments/design.jl

Please take a look, and we comment it tomorrow.

**Comment by santiagobadia** [comment]
Create `ODEOperator` for simpler cases, like `AffineODEOperator`

**Comment by santiagobadia** [comment]
@fverdugo I have created the machinery for `ODETools` in 61cc1552384f3fba3a0232827960bdd47044b421

Can you take a look and make comments?

I have some questions/concerns:
* If we do not consider FE machinery, in `ODETools`, which solvers can we use? From `Julia`? Suggested package? The ones in `Gridap` are more for large problems with linear solvers, etc
* Minor issue with `fill_entries` not defined for standard `Julia` arrays, do we want to put it in `Gridap`?
* Check how I have handled the `cache`. Here I have the most important concern, `cache` is something that we want to be reused at all time steps and thus handled by `ODESolutions` (see `iterate` methods). However, the one generating the `cache` is the `NonlinearOperator` in the `ODESolver`, which is created at every time step. I think it is prompt to error, since we are assuming that these nonlinear operator will generate the same `cache` at all times. I believe it is an acceptable think. We will have to think how to deal with adaptive space discretisation, but I think that this work will be done somewhere else. E.g., provide the time stepper with an error estimator, and stop when remeshing is needed. Then, we start generating a new mesh, project, etc. In any case, it is a quite future development.

**Comment by fverdugo** [comment]
> @fverdugo I have created the machinery for ODETools in 61cc155

Can you take a look and make comments?

I'll take a look.

> If we do not consider FE machinery, in ODETools, which solvers can we use? From Julia? Suggested package? The ones in Gridap are more for large problems with linear solvers, etc

What do you mean by "solver" ? I assume that a time integrator, right? I would start by implementing our own specializations of `ODESolver` e.g., for backward Euler, as you have provably done. Then, we can look if there is some Julia package that returns the computed time steps not in a standard julia array (like DifferentialEquations seems to do by default) but in an iterator. (At this point I am not aware of any package like this, but I haven't do the research...) Then, you can implement an specialization of ODESolution that wraps this iterator, and a specialization of ODESolver that returns this ODESolution specialization.

> Minor issue with fill_entries not defined for standard Julia arrays, do we want to put it in Gridap?

Yes, we should add  a default definition like `fill_entries!(a,ai) = fill!(a,ai)` somewhere in Gridap.Arrays

> Check how I have handled the cache. Here I have the most important concern, cache is something that we want to be reused at all time steps and thus handled by ODESolutions (see iterate methods). However, the one generating the cache is the NonlinearOperator in the ODESolver, which is created at every time step. I think it is prompt to error, since we are assuming that these nonlinear operator will generate the same cache at all times. I believe it is an acceptable think. We will have to think how to deal with adaptive space discretisation, but I think that this work will be done somewhere else. E.g., provide the time stepper with an error estimator, and stop when remeshing is needed. Then, we start generating a new mesh, project, etc. In any case, it is a quite future development.

The cache only works if the underlying non-linear operator has the same sparsity pattern in all time steps and you use the same solver also for all time steps. Obviously, this is true in almost any non-adaptive computation, but not for space adaptivity. In the worse case scenario, the ODESolver can have a user-defined trait that signals if this hypothesis is true or not, and then do dispatch using this trait to use the cache or not. In any case, I wouldn't do this right now. I would wait until we really have space adaptivity

**Comment by fverdugo** [comment]
Suggested renamings:


- GridapTimeStepper -> GridapTimeSteppers (pluralize package name to mach Gridap/julia style)
- jacobian_unknown! -> jacobian!
- jacobian_unknown_t! -> jacobian_t!


ODESolver

- I would not include `get_step_size(::ODESolver)` in the ODESolver interface since it is not general. Some solvers will compute the dt as a part of the solution process (i.e. predictor/corrector schemes). Some other solvers can consider a user-definer non-uniform time discretization, etc. 
- I would only call `solve`  and not `solve_step!` in `test_ode_solver`. Perhaps, some solvers would only implement `solve` and not `solve_step!`. I am thinking of `solve_step!` only as a hook used by the default implementation of `solve` (`solve_step!` is not intended to be called anywhere else).  Thus, if the a type only implements `solve` it is ok and we want the test to pass. In addition, it is oK that `solve_step!` is not exported.
```julia

function test_ode_solver(solver::ODESolver,op::ODEOperator,u0,t0,uf,tf)
   solution = solve(solver,op,u0,t0,tf)
   test_ode_solution(solution)
end
```
- Update the comment on the return type here to include the cache `# -> uF, tF, cache `: 
https://github.com/gridap/GridapTimeStepper.jl/blob/61cc1552384f3fba3a0232827960bdd47044b421/src/ODETools/ODESolvers.jl#L8

ODESolution

- I would not do any numeric check in `test_ode_solution`. The numeric tests will be specific for concrete types. `test_ode_solution` will only check that the interface is implemented and the corresponding methods return the expected types (you will not need any getter):
```julia
function test_ode_solution(sol::GenericODESolution)
  for (u_n,t_n) in sol
    @test isa(t_n,Real)
    @test isa(u_n,AbstractVector)
  end
end
```

BackwardEuler

- Do you really need `allocate_cache` ?
- Move default implementation of `fill_entries!` to Grida.Arrays

**Comment by santiagobadia** [comment]
Ok to everything but first renaming, I don't think we have plural in GridapXXX packages. Only Tutorials. Do you mean to change everything? Even the github repos? Let us discuss it at the end.

I keep `fill_entries!` temporarily here, since I am not using the dev `Gridap` version... I will check how to use in the project.toml the dev version and eliminate it.

With regard to my questions 

> If we do not consider FE machinery, in ODETools, which solvers can we use? From Julia? Suggested package? The ones in Gridap are more for large problems with linear solvers, etc

I just ment how to use a Newton Raphson method without the need to implement it. A Julia package? I think you were playing with some nonlinear solvers. The ones in `Gridap` are more for large problems with sparse linear algebra, etc.

**Comment by fverdugo** [comment]
> Ok to everything but first renaming, I don't think we have plural in GridapXXX packages. Only Tutorials. Do you mean to change everything? Even the github repos? Let us discuss it at the end.

If a module (a package is a module) provides the type `TimeStepper`, we usually call the module `TimeSteppers`. That's why I was thinking of `GridapTimeSteppers`.  I also like the plural since it denotes that the package provides different time steppers, not just one.

> I keep fill_entries! temporarily here, since I am not using the dev Gridap version... I will check how to use in the project.toml the dev version and eliminate it.

The general `fill_entries!` is already in `Gridap#master`. So, you only need  `add Gridap#master` in GridapTimeStepper and remove the unwanted `fill_entries!` definition.

```
(GridapTimeStepper) pkg> add Gridap#master
```

Then add, commit, and push the resulting `Manifest.toml` file. That's all.

> I just ment how to use a Newton Raphson method without the need to implement it. A Julia package? I think you were playing with some nonlinear solvers. The ones in Gridap are more for large problems with sparse linear algebra, etc.

The non-linear solver we use in Gridap (see p-Laplacian tutorial) should work also with dense matrices. Have you tried it?

**Comment by santiagobadia** [comment]
Closed
